name: email-report
version: 1.0.0
icon: "email.svg"

inputs:
- name: FLOWCI_SMTP_CONFIG
  type: string
  required: true

- name: FLOWCI_EMAIL_FROM
  type: string
  required: true

- name: FLOWCI_EMAIL_TO
  type: string
  value: FLOW_USERS
  required: false

script: |
  plugindir=${FLOWCI_AGENT_PLUGIN_DIR}/email-report
  python3 -m pip install Jinja2==2.11.0
  python3 ${plugindir}/src/report.py
