name: email-report
version: 1.0.0
icon: "git.svg"

inputs:
- name: FLOWCI_GIT_URL
  type: string
  required: true

script: |
  plugindir=${FLOWCI_AGENT_PLUGIN_DIR}/email-report
  pip3 install Jinja2
  python3 ${plugindir}/src/report.py
