name: email-notify
version: 1.0.0
icon: "email.svg"

inputs:
- name: FLOWCI_SMTP_CONFIG
  type: string
  required: true

- name: FLOWCI_EMAIL_FROM
  type: string
  required: true

- name: FLOWCI_EMAIL_TO
  type: string
  value: FLOW_USERS
  required: false

docker:
  image: flowci/plugin-email-notify

script: |
  plugindir=${FLOWCI_AGENT_PLUGIN_DIR}/email-report
  python3 ${plugindir}/src/report.py
